nelmio_cors:
  paths:
    '^/api':
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      origin_regex: true
      allow_headers: ['Content-Type', 'Authorization', 'X-License-Key']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
      max_age: 3600
