services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'

  App\License\Application\LicenseLookup:
    alias: App\License\Infrastructure\LicenseRepository

  App\User\Application\UserLookup:
    alias: App\User\Infrastructure\UserRepository
